# Copyright (c) 2016 Qualcomm Technologies International, Ltd.
#   Part of 6.2
# -*-Makefile-*-
# FILE
#   Makefile.inc  -  makefile for the excep module
#
# Name of this subsystem (same as directory name)
SUBSYSTEM=excep

# Source files
SRC_C := excep.c excep_test.c 

# Include standard rules
include Makefile.rules
