/*!
    \copyright Copyright (c) 2018 Qualcomm Technologies International, Ltd.
        All Rights Reserved.
        Qualcomm Technologies International, Ltd. Confidential and Proprietary.
    \version Part of 6.2
    \file chain_output_volume.h
    \brief The chain_output_volume chain. This file is generated by C:/qtil/ADK_QCC512x_QCC302x_WIN_6.2.43/tools/chaingen/chaingen.py.
*/

#ifndef _CHAIN_OUTPUT_VOLUME_H__
#define _CHAIN_OUTPUT_VOLUME_H__

/*!
    @startuml
        object OPR_LATENCY_BUFFER
        OPR_LATENCY_BUFFER : id = CAP_ID_BASIC_PASS
        object OPR_SOURCE_SYNC
        OPR_SOURCE_SYNC : id = CAP_ID_SOURCE_SYNC
        object OPR_VOLUME_CONTROL
        OPR_VOLUME_CONTROL : id = CAP_ID_VOL_CTRL_VOL
        OPR_SOURCE_SYNC "IN(0)"<-- "OUT(0)" OPR_LATENCY_BUFFER
        OPR_VOLUME_CONTROL "MAIN_IN(0)"<-- "OUT(0)" OPR_SOURCE_SYNC
        object EPR_SINK_MIXER_MAIN_IN #lightgreen
        OPR_LATENCY_BUFFER "IN(0)" <-- EPR_SINK_MIXER_MAIN_IN
        object EPR_SINK_MIXER_TONE_IN #lightgreen
        OPR_VOLUME_CONTROL "AUX_IN(1)" <-- EPR_SINK_MIXER_TONE_IN
        object EPR_SOURCE_MIXER_OUT #lightblue
        EPR_SOURCE_MIXER_OUT <-- "OUT(0)" OPR_VOLUME_CONTROL
    @enduml
*/

#include <chain.h>

extern const chain_operator_message_t chain_output_volume_opmsgs_config_common[1];
extern const chain_config_t chain_output_volume_config;

#endif /* _CHAIN_OUTPUT_VOLUME_H__ */

