/****************************************************************************
Generated from E:\TWS_Project\apps\applications\earbud\qcc512x_qcc302x\CF376_CF440\dfu\dfu-public.key
by C:\qtil\ADK_QCC512x_QCC302x_WIN_6.2.43\tools\gen_rsa_pss_constants.py
at 18:01:15 26/02/2018

FILE NAME
    rsa_pss_constants.c

DESCRIPTION
    Constant data needed for the rsa_decrypt and the ce_pkcs1_pss_padding_verify
    function.

NOTES
    The constant data for the rsa_decrypt is generated by the host from the
    RSA public key and compiled into the CONFIG_HYDRACORE VM upgrade library.
    It is directly related to the RSA private and public key pair, and if they
    change then this file must be regenerated from the public key.

****************************************************************************/

#include "rsa_decrypt.h"

/*
 * The const rsa_mod_t *mod parameter for the rsa_decrypt function.
 */
const rsa_mod_t rsa_decrypt_constant_mod = {
    /* uint16 M[RSA_SIGNATURE_SIZE] where RSA_SIGNATURE_SIZE is 128 */
    {
        0xb1b0,     /* 00 */
        0x24ab,     /* 01 */
        0xe15e,     /* 02 */
        0xe502,     /* 03 */
        0xd7f3,     /* 04 */
        0x4a11,     /* 05 */
        0x54a6,     /* 06 */
        0xf428,     /* 07 */
        0x0c73,     /* 08 */
        0x0315,     /* 09 */
        0x8f73,     /* 10 */
        0x6b7a,     /* 11 */
        0xc8e4,     /* 12 */
        0x7942,     /* 13 */
        0x1e73,     /* 14 */
        0xe86b,     /* 15 */
        0xae99,     /* 16 */
        0xe728,     /* 17 */
        0x533e,     /* 18 */
        0x41d3,     /* 19 */
        0x5b15,     /* 20 */
        0x7d4b,     /* 21 */
        0x5dfa,     /* 22 */
        0xcd11,     /* 23 */
        0x924a,     /* 24 */
        0x2fc8,     /* 25 */
        0xa1d8,     /* 26 */
        0x07fe,     /* 27 */
        0x3381,     /* 28 */
        0xa1d1,     /* 29 */
        0xca2f,     /* 30 */
        0x5977,     /* 31 */
        0x0098,     /* 32 */
        0xe9ba,     /* 33 */
        0xe3a4,     /* 34 */
        0x3b34,     /* 35 */
        0x928b,     /* 36 */
        0x580d,     /* 37 */
        0x9567,     /* 38 */
        0x3da5,     /* 39 */
        0xdc05,     /* 40 */
        0xcd7e,     /* 41 */
        0x5495,     /* 42 */
        0x656f,     /* 43 */
        0xf5e0,     /* 44 */
        0x80e0,     /* 45 */
        0x4316,     /* 46 */
        0x8d60,     /* 47 */
        0x1078,     /* 48 */
        0xdfe7,     /* 49 */
        0x2604,     /* 50 */
        0x5d3a,     /* 51 */
        0x8e73,     /* 52 */
        0x4671,     /* 53 */
        0xd832,     /* 54 */
        0x6fb2,     /* 55 */
        0x354a,     /* 56 */
        0xb6f5,     /* 57 */
        0x3b65,     /* 58 */
        0xb2b7,     /* 59 */
        0x8273,     /* 60 */
        0x10aa,     /* 61 */
        0xeb24,     /* 62 */
        0x4793,     /* 63 */
        0x1ae1,     /* 64 */
        0xb821,     /* 65 */
        0x6a6a,     /* 66 */
        0x3324,     /* 67 */
        0xb6d4,     /* 68 */
        0x8a74,     /* 69 */
        0x0373,     /* 70 */
        0x3b7f,     /* 71 */
        0x01db,     /* 72 */
        0x51ef,     /* 73 */
        0xd3c4,     /* 74 */
        0x0ef0,     /* 75 */
        0x6f2b,     /* 76 */
        0x29cf,     /* 77 */
        0x429c,     /* 78 */
        0x9b10,     /* 79 */
        0x6340,     /* 80 */
        0xf0d7,     /* 81 */
        0x8f48,     /* 82 */
        0x50c1,     /* 83 */
        0x3b0a,     /* 84 */
        0x9934,     /* 85 */
        0x2ff3,     /* 86 */
        0x62b1,     /* 87 */
        0x4aa8,     /* 88 */
        0xa932,     /* 89 */
        0x9cd0,     /* 90 */
        0x7fc9,     /* 91 */
        0x2da4,     /* 92 */
        0x538f,     /* 93 */
        0xaa7f,     /* 94 */
        0xb0ef,     /* 95 */
        0x2894,     /* 96 */
        0xad5b,     /* 97 */
        0xb0a8,     /* 98 */
        0x8544,     /* 99 */
        0x7bf5,     /* 100 */
        0x2126,     /* 101 */
        0x0bf1,     /* 102 */
        0x021b,     /* 103 */
        0x7b7c,     /* 104 */
        0xc084,     /* 105 */
        0x5fa1,     /* 106 */
        0xa98a,     /* 107 */
        0x9eb5,     /* 108 */
        0x75fb,     /* 109 */
        0x9937,     /* 110 */
        0x0a5c,     /* 111 */
        0xfd9d,     /* 112 */
        0x4a78,     /* 113 */
        0x1bf1,     /* 114 */
        0x5905,     /* 115 */
        0x5b77,     /* 116 */
        0x858a,     /* 117 */
        0xb0b3,     /* 118 */
        0x91b7,     /* 119 */
        0xe2b8,     /* 120 */
        0xcf50,     /* 121 */
        0x4888,     /* 122 */
        0xee0b,     /* 123 */
        0xab43,     /* 124 */
        0x15f0,     /* 125 */
        0x40a0,     /* 126 */
        0x3179      /* 127 */
    },
    /* uint16 M_dash */
    0x9737
};

/* 
 * The "lump of memory passed in initialised to R^2N mod M" needed for the
 * uint16 *A parameter for the rsa_decrypt function. This must be copied into
 * a writable array of RSA_SIGNATURE_SIZE uint16 from here before use.
 */
const  uint16 rsa_decrypt_constant_sign_r2n[RSA_SIGNATURE_SIZE] = {
    0x2ffb,     /* 00 */
    0x4ed7,     /* 01 */
    0x3906,     /* 02 */
    0x2867,     /* 03 */
    0xcf94,     /* 04 */
    0x5fd2,     /* 05 */
    0x7bad,     /* 06 */
    0x14ac,     /* 07 */
    0xafdf,     /* 08 */
    0xb49a,     /* 09 */
    0xb19d,     /* 10 */
    0xbb3c,     /* 11 */
    0x5f90,     /* 12 */
    0xcdf4,     /* 13 */
    0xe160,     /* 14 */
    0xbe89,     /* 15 */
    0x9ad0,     /* 16 */
    0x79e9,     /* 17 */
    0x3e6e,     /* 18 */
    0x020d,     /* 19 */
    0x7dcd,     /* 20 */
    0x498d,     /* 21 */
    0x5a7b,     /* 22 */
    0x3697,     /* 23 */
    0x4ae1,     /* 24 */
    0x333b,     /* 25 */
    0xf44a,     /* 26 */
    0x50e3,     /* 27 */
    0x3704,     /* 28 */
    0x7b32,     /* 29 */
    0x1cb7,     /* 30 */
    0x7bc4,     /* 31 */
    0x1a93,     /* 32 */
    0xcbf0,     /* 33 */
    0xedd2,     /* 34 */
    0xaaf5,     /* 35 */
    0xa677,     /* 36 */
    0x0416,     /* 37 */
    0xdbbe,     /* 38 */
    0xcca7,     /* 39 */
    0xb115,     /* 40 */
    0x5380,     /* 41 */
    0xa0eb,     /* 42 */
    0x1e90,     /* 43 */
    0xb0d1,     /* 44 */
    0x7e17,     /* 45 */
    0x703e,     /* 46 */
    0x8991,     /* 47 */
    0xd497,     /* 48 */
    0x61fb,     /* 49 */
    0x629c,     /* 50 */
    0xe201,     /* 51 */
    0x20c7,     /* 52 */
    0x1fc4,     /* 53 */
    0xc899,     /* 54 */
    0xfb60,     /* 55 */
    0xeec8,     /* 56 */
    0x8bca,     /* 57 */
    0x0cfd,     /* 58 */
    0x23a6,     /* 59 */
    0x9934,     /* 60 */
    0x242b,     /* 61 */
    0x2752,     /* 62 */
    0x085b,     /* 63 */
    0x2429,     /* 64 */
    0xa235,     /* 65 */
    0x3bf6,     /* 66 */
    0x0efe,     /* 67 */
    0x26b3,     /* 68 */
    0xc22a,     /* 69 */
    0xb152,     /* 70 */
    0x11e9,     /* 71 */
    0xe054,     /* 72 */
    0x4d4a,     /* 73 */
    0x8db3,     /* 74 */
    0x686d,     /* 75 */
    0xeb6a,     /* 76 */
    0xf737,     /* 77 */
    0x891f,     /* 78 */
    0xe46e,     /* 79 */
    0xe529,     /* 80 */
    0xde7e,     /* 81 */
    0x8de4,     /* 82 */
    0xc348,     /* 83 */
    0x4390,     /* 84 */
    0xe829,     /* 85 */
    0xb848,     /* 86 */
    0xb454,     /* 87 */
    0x716e,     /* 88 */
    0x62e3,     /* 89 */
    0xe429,     /* 90 */
    0x1608,     /* 91 */
    0xe0ae,     /* 92 */
    0xeaf4,     /* 93 */
    0x46ae,     /* 94 */
    0x0662,     /* 95 */
    0xf2cb,     /* 96 */
    0xdd50,     /* 97 */
    0x65aa,     /* 98 */
    0xd783,     /* 99 */
    0x5252,     /* 100 */
    0xf466,     /* 101 */
    0xfed0,     /* 102 */
    0x495a,     /* 103 */
    0xc1d6,     /* 104 */
    0x060e,     /* 105 */
    0xc323,     /* 106 */
    0x274e,     /* 107 */
    0x926f,     /* 108 */
    0xd201,     /* 109 */
    0x5732,     /* 110 */
    0x53e8,     /* 111 */
    0x87bf,     /* 112 */
    0x6450,     /* 113 */
    0x245b,     /* 114 */
    0x3aa5,     /* 115 */
    0xae95,     /* 116 */
    0xa769,     /* 117 */
    0xd97b,     /* 118 */
    0xf25d,     /* 119 */
    0x4cad,     /* 120 */
    0x465d,     /* 121 */
    0xd745,     /* 122 */
    0x9604,     /* 123 */
    0x36f9,     /* 124 */
    0x2bee,     /* 125 */
    0x9157,     /* 126 */
    0xb6b8      /* 127 */
};

/*
 * The value to be provided for the saltlen parameter to the 
 * ce_pkcs1_pss_padding_verify function used to decode the PSS padded SHA-256
 * hash. It has to match the value that was used in the encoding process.
 */
const unsigned long ce_pkcs1_pss_padding_verify_constant_saltlen = 222;
