# Copyright (c) 2016 Qualcomm Technologies International, Ltd.
#   Part of 6.2
# -*-Makefile-*-
# FILE
#   Makefile.inc  -  makefile for id
#

# Name of this subsystem (same as directory name)
SUBSYSTEM=	id

SRC_C=	id.c

SLT_ENTRY_H=	id_slt_entry.h

# Include standard rules
include Makefile.rules
