/**************************************************************************/
/* Copyright (c) 2018 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           5002

#define PATCH_ENTRY_CREATE_MUTE_OP               0x040027ad /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x040027e7 /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x040027ed /* $_cbops_mute_reset */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
