# Copyright (c) 2016 Qualcomm Technologies International, Ltd.
#   Part of 6.2
# -*-Makefile-*-
# FILE
#   Makefile.inc  -  makefile for the memprot module
#
# Name of this subsystem (same as directory name)
SUBSYSTEM=memprot

# Source files
SRC_C := memprot.c memprot_test.c 

# Include standard rules
include Makefile.rules
