# Copyright (c) 2016 Qualcomm Technologies International, Ltd.
#   Part of 6.2
# -*-Makefile-*-
# FILE
#   Makefile.inc  -  makefile for this module
#

# Name of this subsystem (same as directory name)
SUBSYSTEM = pl_timers

# Source files
SRC_C = pl_timers.c

SRC_S =

# Include standard rules
include Makefile.rules
